name: line_drawer_app
description: A new Flutter project.
version: 1.0.1+2
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_database: ^10.3.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true